modLoader="javafml"
loaderVersion="[47,)"
license="Academic Free License v3.0"

[[mods]]
modId="apotheotic_additions"
version="2.0.1"
displayName="Apotheotic Additions"
credits="Apotheosis Addon"
displayURL="https://mcreator.net"
authors="Bryce792, MCreator"

[[dependencies.apotheotic_additions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




