modLoader="javafml"
loaderVersion="[47,)"
license="Academic Free License v3.0"

[[mods]]
modId="apotheotic_additions"
version="1.2"
displayName="Apotheotic Additions"
credits="Adds in more Apotheosis Compat."
displayURL="https://github.com/Bryce792/ApotheoticAdditions/tree/main"
authors="Bryce792, MCreator"

[[dependencies.apotheotic_additions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




